name: Dead Links
description: Run Dead Links Tests
runs:
  using: "composite"
  steps:
    - name: Prepare kuzdoc
      run: |
        npm ci
        npm run doc-prepare
        $(npm bin)/kuzdoc iterate-repos:install --repos_path .doc/framework/.repos/
        $(npm bin)/kuzdoc framework:link -d /sdk/go/3 -v 3 --base_root .doc/
      shell: bash
    - name: Run Dead Links
      run: |
        sudo gem install typhoeus
        cd .doc/framework/ && HYDRA_MAX_CONCURRENCY=20 ruby .ci/dead-links.rb -p src/sdk/go/3
      shell: bash
