name: Run tests

on: [pull_request]

jobs:
  docs:
    name: Documentation Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.x"
      - run: docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index


  docs-linux-amd64-go-1-15-x:
    name: Linux amd64 go 1.15.X
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.x"
      - uses: ./.github/actions/docs
        with:
          os: linux
          arch: amd64
          command: ./.ci/test_with_coverage.sh

  docs-linux-i386:
    name: Go ${{ matrix.go-version }} on ${{ matrix.arch }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [386]
        go-version: [1.15.x, 1.11.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: ./.github/actions/docs
        with:
          os: linux
          arch: ${{ matrix.arch }}
          command: sudo go test -v ./...

  docs-linux-arm64:
    name: Go ${{ matrix.go-version }} on ${{ matrix.arch }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]
        go-version: [1.15.x, 1.11.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: sudo apt install qemu-user-static -y
      - uses: ./.github/actions/docs
        with:
          os: linux
          arch: ${{ matrix.arch }}
          command: sudo taskset -c 1 go test -v -exec "qemu-aarch64-static" ./...

  docs-linux-armhf:
    name: Go ${{ matrix.go-version }} on ${{ matrix.arch }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm]
        go-version: [1.15.x, 1.11.x, 1.10.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: sudo apt install qemu-user-static -y
      - uses: ./.github/actions/docs
        with:
          os: linux
          arch: ${{ matrix.arch }}
          goarm: 7
          command: sudo taskset -c 1 go test -v -exec "qemu-aarch64-static" ./...

  docs-macos:
    name: Go ${{ matrix.go-version }} on ${{ matrix.arch }} 
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, 386]
        go-version: [1.15.x, 1.11.x, 1.10.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: ./.github/actions/docs
        with:
          os: darwin
          arch: ${{ matrix.arch }}
          command: go test -v ./...


  docs-windows-amd64:
    name: windows amd64 go 1.15.X
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, 386]
        go-version: [1.15.x, 1.11.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: ./.github/actions/docs
        with:
          os: windows
          arch: ${{ matrix.arch }}
          command: go test -v ./...

  dead-links:
     name: Dead Links
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Cache node modules
         uses: actions/cache@v2
         env:
           cache-name: cache-node-modules
         with:
           path: ~/.npm
           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}-
             ${{ runner.os }}-build-
             ${{ runner.os }}-
       - uses: actions/setup-node@v1
         with:
           node-version: "12"
       - uses: ./.github/actions/dead-links

  docs-tests:
    name: Docs Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.x"
      - run: docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index
