name: Deployment Doc Prod

on:
  push:
    branches:
      - master
      - 1-stable
      - 2-stable

jobs:
  docs:
    name: Documentation Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.x"
      - run: docker-compose -f .ci/doc/docker-compose.yml run doc-tests node index


  tests-linux-amd64-go-1-15-x:
    name: Linux go ${{ matrix.go-version }} on ${{ matrix.arch }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch: [amd64]
        go-version: [1.15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: ./.github/actions/tests
        with:
          os: linux
          arch: ${{ matrix.arch }}
          command: ./.ci/test_with_coverage.sh

  tests-linux-i386:
    name: Linux go ${{ matrix.go-version }} on ${{ matrix.arch }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch: [386]
        go-version: [1.15.x, 1.11.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: ./.github/actions/tests
        with:
          os: linux
          arch: ${{ matrix.arch }}
          command: sudo go test -v ./...

  tests-macos:
    name: MacOS go ${{ matrix.go-version }} on ${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, 386]
        go-version: [1.15.x, 1.11.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: ./.github/actions/tests
        with:
          os: darwin
          arch: ${{ matrix.arch }}
          command: go test -v ./...


  tests-windows:
    name: Windows go ${{ matrix.go-version }} on ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, 386]
        go-version: [1.15.x, 1.11.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: ./.github/actions/tests
        with:
          os: windows
          arch: ${{ matrix.arch }}
          command: go test -v ./...

  doc-prod:
    name: Deploy docs.kuzzle.io
    runs-on: ubuntu-18.04
    needs: [docs, tests-linux-amd64-go-1-15-x, tests-linux-i386, tests-macos, tests-windows]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: ./.github/actions/doc-deploy
        with:
          NODE_ENV: production
          S3_BUCKET: docs.kuzzle.io
          CLOUDFRONT_DISTRIBUTION_ID: E3D6RP0POLCJMM
          AWS_DEFAULT_REGION: us-west-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
